### PR TITLE
Add build_local.jl scripts that pulls the correct jlls

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
@Gnimuc if you don't like copying the libclang files directly, we could also pull the source from `https://github.com/JuliaLang/llvm-project/archive/refs/tags/julia-14.0.5-2.tar.gz`.

**Review by Gnimuc — APPROVED** [review]
Thanks for working on this!

**Comment by Gnimuc** [comment]
@vchuravy As for multi-version support, I'm a little bit worried about enums because manually updating enums is very likely to be error-prone and those bugs caused by the enum mismatch are not easy to reason about.

**Comment by vchuravy** [comment]
That's a reasonable worry :) but thankfully there is this fantastic tool call Clang.jl ;) that let's you auto-generate the bindings. Joking aside, this is what we do for LLVM.jl https://github.com/maleadt/LLVM.jl/tree/master/lib

**Comment by Gnimuc** [comment]
I think this is a great chance to write a tool to generate C enums from C++ enums and can be configured to have multi-version compatibility. 😈

**Pull request merged**
